# Generated by Django 2.2.6 on 2019-10-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_organizador', models.CharField(max_length=100)),
                ('id_usuario', models.CharField(max_length=100)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('ubicacion', models.TextField(help_text='Especifica Ubiacion')),
                ('detalles_evento', models.TextField(help_text='Especifica detalles')),
                ('cupo', models.IntegerField(null=True)),
                ('fecha_evento', models.DateTimeField()),
            ],
        ),
    ]
