# Generated by Django 2.2.6 on 2019-10-09 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_organizador', models.CharField(max_length=100)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('ubicacion', models.TextField(help_text='Especifica Ubiacion')),
                ('detalles_evento', models.TextField(help_text='Especifica detalles')),
                ('cupo', models.IntegerField(null=True)),
                ('fecha_inicio_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin_evento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_evento', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('contraseña_usuario', models.CharField(max_length=40)),
                ('correo_usuario', models.EmailField(blank=True, max_length=254, unique=True)),
                ('confirmacion_usuario', models.BooleanField(default=False)),
                ('statf', models.BooleanField(default=False)),
                ('sexo_usuario', models.CharField(max_length=200)),
                ('pasatiempos_usuario', models.TextField(help_text='Redacta tus pasatiempos')),
                ('entidad_academica_usuario', models.CharField(max_length=100)),
                ('foto_usuario', models.TextField(help_text='se usara ImageField')),
            ],
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
