# Generated by Django 2.2.6 on 2019-10-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20191009_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
