# Generated by Django 2.2.6 on 2019-10-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('web', models.URLField(blank=True)),
                ('id_evento', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('contraseña_usuario', models.CharField(max_length=40)),
                ('confirmacion_usuario', models.BooleanField(default=False)),
                ('statf', models.BooleanField(default=False)),
                ('sexo_usuario', models.CharField(max_length=200)),
                ('pasatiempos_usuario', models.TextField(help_text='Redacta tus pasatiempos')),
                ('entidad_academica_usuario', models.CharField(max_length=100)),
                ('foto_usuario', models.TextField(help_text='se usara ImageField')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
