# Generated by Django 2.2.6 on 2019-10-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre_usuario']},
        ),
    ]
