# Generated by Django 2.2.6 on 2019-10-09 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_organizador', models.CharField(max_length=100)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('ubicacion', models.TextField(help_text='Especifica Ubiacion')),
                ('detalles_evento', models.TextField(help_text='Especifica detalles')),
                ('cupo', models.IntegerField(null=True)),
                ('fecha_inicio_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin_evento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
