# Generated by Django 2.2.6 on 2019-10-21 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['nombre_evento']},
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_fin_evento',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio_evento',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
